# Generated by Django 5.2.11 on 2026-02-09 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('social_twitter', 'Social Media - Twitter/X'), ('social_instagram', 'Social Media - Instagram'), ('social_tiktok', 'Social Media - TikTok'), ('social_linkedin', 'Social Media - LinkedIn'), ('press_release', 'Press Release'), ('news_article', 'News Article'), ('ad_digital', 'Digital Advertisement'), ('ad_tv', 'TV Advertisement'), ('email', 'Email'), ('internal_memo', 'Internal Memo'), ('policy_announcement', 'Policy Announcement'), ('other', 'Other')], max_length=50)),
                ('scenario_tag', models.CharField(choices=[('product_launch', 'Product Launch'), ('campaign', 'Marketing Campaign'), ('crisis', 'Crisis Response'), ('policy', 'Policy Announcement'), ('rebrand', 'Rebranding'), ('csr', 'CSR Initiative'), ('earnings', 'Earnings/Financial'), ('leadership', 'Leadership Change'), ('other', 'Other')], max_length=50)),
                ('context_text', models.TextField(help_text='Background context for the scenario')),
                ('message_text', models.TextField(help_text='The actual message being tested')),
                ('sender_name', models.CharField(blank=True, help_text='Who is sending this message', max_length=255)),
                ('target_action', models.CharField(blank=True, help_text='What action do we want audience to take', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimuli', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Stimuli',
                'ordering': ['-created_at'],
            },
        ),
    ]
