# Generated by Django 5.2.11 on 2026-02-09 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(choices=[('MENA', 'Middle East & North Africa'), ('GCC', 'Gulf Cooperation Council'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('EG', 'Egypt'), ('GLOBAL', 'Global')], default='MENA', max_length=20)),
                ('primary_language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('ar-sa', 'Arabic (Saudi)'), ('ar-eg', 'Arabic (Egyptian)'), ('ar-ae', 'Arabic (Emirati)')], default='en', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
