# Generated by Django 5.2.11 on 2026-02-09 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiences', '0001_initial'),
        ('projects', '0001_initial'),
        ('stimuli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial (some errors)')], default='pending', max_length=20)),
                ('phases', models.JSONField(default=list, help_text="List of phases to run, e.g. ['D1', 'D7']")),
                ('agent_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('error_count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='projects.project')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='audiences.audiencesegment')),
                ('stimulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='stimuli.stimulus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(max_length=10)),
                ('response_count', models.IntegerField(default=0)),
                ('avg_approval', models.FloatField(default=0)),
                ('approval_distribution', models.JSONField(default=dict, help_text='Counts per score bucket')),
                ('emotion_means_json', models.JSONField(default=dict)),
                ('intent_counts_json', models.JSONField(default=dict)),
                ('top_themes_json', models.JSONField(default=list, help_text='Extracted themes from verbatims')),
                ('representative_quotes', models.JSONField(default=list, help_text='Sample verbatims')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='simulations.simulationrun')),
            ],
            options={
                'ordering': ['phase'],
                'unique_together': {('run', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='AgentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(max_length=10)),
                ('approval_score', models.IntegerField()),
                ('emotions_json', models.JSONField(default=dict)),
                ('intent_label', models.CharField(max_length=50)),
                ('intent_confidence', models.FloatField()),
                ('verbatim_text', models.TextField()),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='audiences.agentprofile')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='simulations.simulationrun')),
            ],
            options={
                'ordering': ['phase', 'agent__display_name'],
                'unique_together': {('run', 'agent', 'phase')},
            },
        ),
    ]
