# Generated by Django 5.2.11 on 2026-02-09 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('demographics_json', models.JSONField(default=dict, help_text='Age range, gender split, location, income, education')),
                ('style_guide_json', models.JSONField(default=dict, help_text='Communication style, formality, emoji usage, dialect')),
                ('attitudes_json', models.JSONField(default=dict, help_text='Attitudes toward key topics, brands, values')),
                ('engagement_json', models.JSONField(default=dict, help_text='Platform preferences, posting frequency, influence level')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=100)),
                ('traits_json', models.JSONField(default=dict, help_text='Specific demographics, personality, values')),
                ('memory_text', models.TextField(blank=True, help_text="Agent's memory from previous phases")),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='audiences.audiencesegment')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
